use_frameworks!

platform :ios, '9.0'

target 'MyLibTest_Example' do
  pod 'MyLibTest', :path => '../'

  target 'MyLibTest_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
